name: TitanTools
version: '${project.version}'
main: com.nessxxiii.titantools.TitanTools
api-version: 1.19
authors: [ bfrisco, NessXXIII ]
description: Custom enchantments for Theatria
commands:
  titan:
    description: Dev tools for titanEnchants
    usage: |
      /<command> reload
  atitan:
  tkit:
    description: kit commands for titan tools, crystals and other custom items
    usage: |
      /<command> <kit_type>
  crystal:
    description: power crystal commands
    usage: |
      /<command> give
      /<command> check
      /<command> give <type> <amount>
  theatriatool:
    description: theatriatool commands
    usage: |
      /<command> give <type> <amount>