name: TitanTools
version: '${project.version}'
main: com.nessxxiii.titantools.TitanTools
api-version: 1.19
authors: [ bfrisco, NessXXIII ]
description: Custom enchantments for Theatria
commands:
  titan:
    description: Dev tools for titanEnchants
    usage: |
      /<command> <subcommand>