name: TitanEnchants
version: '${project.version}'
main: com.nessxxiii.titanenchants.TitanEnchants
api-version: 1.19
authors: [ bfrisco, NessXXIII ]
description: Custom enchantments for Theatria
softdepend: [mcMMO]
commands:
  titan:
    description: Dev tools for titanEnchants
    usage: |
      /<command> reload